### ISSUE TITLE
Slate demo does not work :(

### ISSUE THREAD

**Issue by eyalmmm** [grammarly/javascript-plugin#1]
https://developer.grammarly.io/slate
The one mentioned in the readme: 
![image](https://user-images.githubusercontent.com/15931001/104315513-c0917680-54e3-11eb-9f5b-68e5fde80ee8.png)

**Comment by wachunga** [comment]
Thanks for reporting the broken link. Unfortunately, the actual link is not yet public as we're in a closed beta for now. Stay tuned!
