### ISSUE TITLE
Is there a way to participate?

### ISSUE THREAD

**Issue by Lisennk** [grammarly/javascript-plugin#2]
Hi, Grammarly team. 

I am very excited about the public plugin, since all other public solutions, such as GrammarBot/LanguageTool, does not really work for us. 

Is there a way to participate in closed beta?

**Comment by chernetsov** [comment]
Thanks for reaching out, @Lisennk! I am on the team that works on this project here at Grammarly. Could you please contact me directly for further discussion: michael.chernetsov@grammarly.com
