### ISSUE TITLE
how to get clientId

### ISSUE THREAD

**Issue by Tosn** [grammarly/javascript-plugin#6]

**Comment by chernetsov** [comment]
Hello, @Tosn. Thank you for your interest! This product is not launched yet. Could you please fill in early access form?
https://docs.google.com/forms/d/1uQbzN6WLQkDz586MszwyJVy_QMPKi5cmPEl6kjGlM80/edit

**Comment by Tosn** [comment]
> Hello, @Tosn. Thank you for your interest! This product is not launched yet. Could you please fill in early access form?
> https://docs.google.com/forms/d/e/1FAIpQLSeXHBCuH3h6r8Gf06o1IBWZiLyWFT7TsC9DebnkdVPguIRejA/viewform

thanks
