### ISSUE TITLE
Is the sdk functional without browser plugin? 

### ISSUE THREAD

**Issue by gregory-h** [grammarly/javascript-plugin#7]
We have applied for early access and are reviewing the VueJs examples, but noticing that they function as normal inputs/textareas (with no grammarly functionality etc) unless the chrome extension is also installed. 

Could you clarify if there is a dependency on the browser plugin? We'd like to understand the scope of the grammarly integration that we could offer and what actions our customers would need to take in order to enable it.

**Comment by wachunga** [comment]
Hi @gregory-h there's no dependency on the chrome extension at all. You can try completely disabling the extension (from browser settings) to verify this, or use a browser that doesn't have the extension installed.

There have been issues occasionally with the SDK and extension interfering with each other, though, especially on codesandbox (which uses iframes).

If you provide a repro of some kind, we can take a closer look.

**Comment by gregory-h** [comment]
Thanks for the clarification @wachunga. I tried serving the vue-textarea example as-is, but wasn't seeing any grammarly functionality there with or without the chrome extension installed. Looking at it again I do see an oauth error in the console, so I'm assuming the problem is just an invalid clientId?

**Comment by znck** [comment]
The `vue-textarea` example is outdated. Try [examples/editor-sdk-vue](https://github.com/grammarly/javascript-plugin/tree/main/examples/editor-sdk-vue) ([open in codesandbox](https://githubbox.com/grammarly/javascript-plugin/tree/main/examples/editor-sdk-vue)) for latest examples.

**Comment by gregory-h** [comment]
Awesome - thanks.
